### ISSUE TITLE
helpers.go: bug: underscore in fields are missing when printing in YAML format

### ISSUE THREAD

**Issue by bzon** [devopsctl/gitlabctl#114]
Underscore are missing when printing in yaml format.

Test command: `get groups -o yaml`

```yaml
- id: 13
  name: Group1
  path: Group1
  description: Updated by go test by id
  visibility: private
  lfsenabled: false # this should be lfs_enabled
  avatarurl: "" # this should be avatar_url
  weburl: http://localhost:10080/groups/Group1 # this should be web_url
  requestaccessenabled: false  # this ..
  fullname: Group1  # this ..
  fullpath: Group1  # this ..
  parentid: 0  # this ..
  projects: []
  statistics: null
```

The current code is in https://github.com/devopsctl/gitlabctl/blob/master/cmd/helpers.go#L131:

```golang
func printYAML(v interface{}) {
	b, err := yaml.Marshal(v)
	if err != nil {
		er(fmt.Sprintf("failed printing to yaml: %v", err))
	}
	fmt.Println(string(b))
}
```
